### PR TITLE
Karlsbranch

### PR DESCRIPTION
**Pull request by behrenskarl**
adding skeleton html, css, javascript files

### CODE REVIEW

**Review by DavidVDeaton — DISMISSED** [review]
fantastic! great work.

**Review by wmwassmann — DISMISSED** [review]
Awesome API work! :D :D 🗡️

**Review by DavidVDeaton — DISMISSED** [review]
Old. Ignore this.

**Review by DavidVDeaton — COMMENTED** [review]
old files

**Review by DavidVDeaton — COMMENTED** [review]
I think we got this figured out.

**Review by DavidVDeaton — APPROVED** [review]

**Pull request merged**
